# 一、ndarray
##  1.ndarray的特性
### 多维性


In [2]:
import numpy as np

In [3]:
import pandas as  pd

In [4]:
arr = np.array(5)  # 创建0维的ndarray数组
print(arr)
print('arr的维度：', arr.ndim) # number of dimensions

5
arr的维度： 0


In [5]:
arr = np.array([1,2,3])  # 创建1维的ndarray数组
print(arr)
print('arr的维度：', arr.ndim) # number of dimensions

[1 2 3]
arr的维度： 1


In [6]:
arr = np.array([[1,2,3],[4,5,6]])  # 创建2维的ndarray数组
print(arr)
print('arr的维度：', arr.ndim) # number of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度： 2


### 同质性

In [7]:
arr = np.array([1,'Hello']) # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

['1' 'Hello']


In [8]:
arr = np.array([1,2.5]) # 不同的数据类型会被强制转换成相同的数据类型
print(arr)

[1.  2.5]


## 2.ndarray的属性 

In [9]:
arr = np.array(1)
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)

1
数组的形状： ()
数组的维度： 0
元素的个数： 1
元素的数据类型： int64


In [10]:
arr = np.array([1,2.5,3])
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)
print('元素的转置：',  arr.T)

[1.  2.5 3. ]
数组的形状： (3,)
数组的维度： 1
元素的个数： 3
元素的数据类型： float64
元素的转置： [1.  2.5 3. ]


In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的数据类型：', arr.dtype)
print('元素的转置：',  arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
数组的维度： 2
元素的个数： 6
元素的数据类型： int64
元素的转置： [[1 4]
 [2 5]
 [3 6]]


## 3.ndarray的创建

In [12]:
# 基础的创建方法
list1  = [4,5,6]
arr = np.array(list1,dtype=np.float64)
print(arr.ndim)  # 属性
print(arr)


1
[4. 5. 6.]


In [13]:
#  copy
arr1 = np.copy(arr)  # 元素跟原始的数组相同，但是不是一个数组了
print(arr1)
arr1[0] = 8
print(arr1)
print(arr)

[4. 5. 6.]
[8. 5. 6.]
[4. 5. 6.]


In [14]:
# 预定义形状
# 全0  全1 未初始化 固定值

# 全0
arr  = np.zeros((2,3),dtype  = int)
print(arr)
print(arr.dtype)

[[0 0 0]
 [0 0 0]]
int64


In [15]:
# 预定义形状
# 全0  全1 未初始化 固定值

# 全0
arr  = np.zeros((200,),dtype  = int)
print(arr)
print(arr.ndim)  # 这是一维的

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1


In [16]:
#  全1
arr =  np.ones((5,8),dtype =  int)
print(arr)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [17]:
# 未初始化
arr = np.empty((2,3))
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
# 第二次改一下格式 初始化后的
arr = np.empty((4,3))
print(arr)


[[1.37724385e-311 2.47032823e-322 0.00000000e+000]
 [0.00000000e+000 6.23047502e-307 1.33664410e+160]
 [4.96393730e-090 4.85407820e-033 1.28344109e+160]
 [1.43824387e-051 3.99910963e+252 2.12895739e-052]]


In [19]:
arr = np.full((3,4),2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [20]:
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr,2026)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[      2787572592488                  50                   0
                    0]
 [7019813712450027520 7002653653508187499 3270802121510184548
  4123384302655518309]
 [7002312799567293749 3846417354404684085 8386112019188769379
  3474302134482400117]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [21]:
# 等差数列 2 4 6 8 10
arr =  np.arange(2,11,2) # start,end,step（步长）
print(arr)

[ 2  4  6  8 10]


In [22]:
#等间隔数列
arr = np.linspace(0,100,5,dtype=int) #  第三个是取几份
print(arr)
arr =  np.arange(0,101,25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [23]:
# 对数间隔数列  （其实是指数 等比数列）不写默认是10
arr =  np.logspace(0,4,3,base=2)
print(arr)

[ 1.  4. 16.]


In [24]:
# 特殊矩阵
# 单位矩阵：主对角线上的数字为1，其他的数字为0
arr = np.eye(3,4,dtype =int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [25]:
# 对角矩阵：主对角线上非零的0，其他的数字为0
arr = np.diag([5,1,2,3])
print(arr)

[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


In [26]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2,3)
print(arr)

[[0.58355851 0.43446764 0.94249626]
 [0.57014683 0.12169812 0.32048893]]


In [27]:
# 生成指定范围区间的随机浮点数 （均匀分布）
arr =  np.random.uniform(3,6,(2,3))
print(arr)

[[3.55183881 5.19298172 3.36540341]
 [3.38097978 4.95425444 4.19382869]]


In [32]:
#  生成指定范围区间的随机整数
arr = np.random.randint(3,30,(2,3))
print(arr)
  

[[27 25 19]
 [20  7 13]]


In [ ]:
# 生成随机数列（正态分布）（-3到3之间）
# 两边概率小 中间大 
arr =  np.random.randn(2,3)
print(arr)

[[-0.13175994 -1.42579149  0.86783206]
 [ 1.10255041 -0.16918462 -1.82566936]]


In [35]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]
